### ISSUE TITLE
Node warning while installing ember-sass-bootstrap

### ISSUE THREAD

**Issue by HenryVonfire** [ef4/ember-sass-bootstrap#3]
I got this warning while installing this addon:

> (node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.
> Trace
>     at process.addListener (events.js:239:17)
>     at Object.<anonymous> ([app_path]/node_modules/ember-sass-bootstrap/node_modules/broccoli-stew/node_modules/broccoli-merge-trees/node_modules/can-symlink/node_modules/tmp/lib/tmp.js:449:9)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> ([app_path]/node_modules/ember-sass-bootstrap/node_modules/broccoli-stew/node_modules/broccoli-merge-trees/node_modules/can-symlink/index.js:1:73)
>     at Module._compile (module.js:409:26)

**Comment by ef4** [comment]
Thanks for the bug report.

That warning is not specific to this addon, it's an unfortunate side effect of poor defaults in node. [A recent change in ember-cli](https://github.com/ember-cli/ember-cli/pull/5987/commits/a77ede27cdc5b7cdf882ff1db9ffead822bdb9c6) will make the warning go away.

**Comment by HenryVonfire** [comment]
Thanks for your quick answer, I thought it was related to this addon because it was generated during the installation and the main addon that appears in the paths was this one too.
