### ISSUE TITLE
Documentation on controlling plugin javascript inclusion is incorrect

### ISSUE THREAD

**Issue by ScottSmix** [ef4/ember-sass-bootstrap#6]
The documentation states to add:

bootstrap: {
  plugins: []
}

But based on a glance of the code, it just loads plugins (not bootstrap.plugins) and so expects:

plugins: []

**Comment by ef4** [comment]
Good catch. This got broken unintentionally in https://github.com/ef4/ember-sass-bootstrap/pull/5

cc @selvaa89

**Comment by selvaa89** [comment]
I will fix this and raise a PR.

**Comment by ef4** [comment]
Fix published as 0.1.2. Thanks for the bug report and thanks @selvaa89 for a quick followup.
